### ISSUE TITLE
Add a default argument

### ISSUE THREAD

**Issue by timkelty** [jpcercal/environment#4]
It would be great if you could pass a second argument as the default value, if the env var isn't set.

Currently, I have to do this:

```
$enableIndexing = getenv('ENABLE_INDEXING') !== false ? Environment::get('ENABLE_INDEXING') : true;
```

Would be great if I could just do:

```
$enableIndexing = Environment::get('ENABLE_INDEXING', true);
```

**Comment by jpcercal** [comment]
Hi @timkelty your suggestion is interesting to this project. I implemented this feature in the version 0.1.0.

Thanks for your contribution.
